sudo: required
services:
    - docker

script:
    - docker-compose build
    - docker images ngshiheng/*

before_deploy:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
    provider: script
    script: docker-compose push
    on:
        branch: master
