version: "3"
services:
    server:
        container_name: server
        restart: always
        build: ./server
        image: ngshiheng/server
        ports:
            - "4000:4000"
    client:
        container_name: client
        restart: always
        build: ./client
        image: ngshiheng/client
        ports:
            - "3000:3000"
        links:
            - server
